---
- name: Install Linux Universal Forwarder
  hosts: '{{ host }}'
  vars:
    splunk_working_directory: '/tmp/Splunk/'
    splunk_uf_file_centos: 'splunkforwarder-7.2.3-06d57c595b80-Linux-x86_64.tgz'
    splunk_uf_file_arm: 'splunkforwarder-7.2.3-06d57c595b80-Linux-arm.tgz'
  roles:
    - common