---
- name: Install packages
  hosts: '{{all}}'
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - epel-release
       - wget 
       - unzip
       - mariadb-server
       - ansible
       - git
      ignore_errors: true

    - name: Install splunk forwarder
      shell: "wget -O splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.3&product=universalforwarder&filename=splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz&wget=true'"
      
    - name: Copy file
      shell: cp splunkforwarder-8.0.3-a6754d8441bf-Linux-x86_64.tgz /opt/splunk/