key_name: "bastion_host"
instance_type: "t2.micro"
image: "ami-0323c3dd2da7fb37d"
group: "default"
count: 1
vpc_subnet_id: "subnet-00e2676aab13f44e5"
assign_public_ip: yes
region: "us-east-1"

key_name: "bastion_host"
instance_type: "t2.micro"
image: "ami-0f310fced6141e627"
group: "default"
count: 1
vpc_subnet_id: "subnet-3c944417"
assign_public_ip: yes
region: "ap-northeast-1"

key_name: "bastion_host"
instance_type: "t2.micro"
image: "ami-01a6e31ac994bbc09"
group: "default"
count: 1
vpc_subnet_id: "subnet-09dcc9535d972ec97"
assign_public_ip: yes
region: "eu-west-2"

