---
- name: My First Task
  hosts: us-west-2
  become: true
  become_method: sudo
  tasks: 
  - name: Install package
    package: 
      name: httpd
      state: installed
    
  
  - name: Install Telnet
    package: 
      name: telnet
      state: installed

   - name: copy ssh key
      authorized_key:
        key: "{{ lookup('file', ssh_key) }}"
        user: centos
   
   - name: Add Bob
    user: 
      name: user
      state: present

  - name: Add Ben
    user: 
      name: user
      state: present

  - name: Add Lisa
    user: 
      name: user
      state: present

  - name: Add Katy
    user: 
      name: user
      state: present
