- name: Check if Splunk already installed
  stat:
    path: '/opt/splunkforwarder'
  register: splunk_path_present
 
- name: Check if Splunk forwarder package already transferred - CentOS
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_centos}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] == "CentOS"
 
- name: Check if Splunk forwarder package already transferred - Raspberry Pi
  stat:
    path: "{{splunk_working_directory}}{{splunk_uf_file_arm}}"
  register: splunk_installer_present
  when:
    - ansible_facts['distribution'] != "CentOS"