- name: Waiting for the instance to come
        local_action: wait_for
                      host={{ item.public_ip }}
                      state=started
                      port=22 9997
        with_items: ec2.instances