---
- name: Handler
  hosts: 54.190.14.224
  become: true
  become_method: sudo
  ignore_errors: false
  handlers:
    - name: HTTPD RESTART
      systemd: 
        name: httpd 
        state: restarted
    - name: MYSQL RESTART
      systemd: 
        name: mysqld 
        state: restarted
  tasks:
    - name: Handler tasks
      package: 
        name: httpd
        state: latest
      notify: HTTPD RESTART 
    - name: Install mysql
      package: 
        name: mariadb-server
        state: present
      notify: MYSQL RESTART
  