---
- name: My First Playbook
  hosts: all
  become: true
  become_method: sudo
  tasks: 
  - name: Install package
    package: 
      name: httpd
      state: installed
    
  
  - name: Install Telnet
    package: 
      name: telnet
      state: installed

  - name: Add Bob
    user: 
      name: user
      state: absent