---
- name: My First Task
  hosts: 18.237.186.94
  become: true
  become_method: sudo
  tasks: 
  - name: Install package
    package: 
      name: httpd
      state: installed
    
  
  - name: Install Telnet
    package: 
      name: telnet
      state: installed

  - name: Run ssh-keygen
    package: 
      name : ssh-keygen
      state: created

  - name: Add Bob
    user: 
      name: user
      state: present

  - name: Add Ben
    user: 
      name: user
      state: present

  - name: Add Lisa
    user: 
      name: user
      state: present

  - name: Add Katy
    user: 
      name: user
      state: present