---
- name: Installs wordpress
  hosts: 54.190.14.224
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - epel-release
       - wget 
       - unzip
       - mysql-server
      ignore_errors: true

    - name: Install epel-release
      shell: "yum install http://rpms.remirepo.net/enterprise/remi-release-6.rpm -y"
      args: 
        creates: /etc/yum.repos.d/remi.repo
    
    - name: config manager enabled 
      shell: "yum-config-manager --enable remi-php72"
    
    - name : update httpd PHP 
      shell: "yum install httpd php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql mysql -y" 

    - name: Download wordpress Package
      get_url:
        url: https://wordpress.org/wordpress-5.2.1.tar.gz
        dest: /tmp/

    - name: Unzip wordpres file
      unarchive:
        src: "/tmp/wordpress-5.2.1.tar.gz"    
        dest: "/var/www/html"
        remote_src: yes

    - name: Restart apache
      service:
        name: httpd
        state: restarted  
        enabled: yes
        
