---
- name: Zip Logs Over 100M
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks: 
  - name: Install package
    shell: "sudo find /var/log -type f -name "*.log" -size +100M -exec gzip -v9 {} +"
  
  